### ISSUE TITLE
Toggle not working Navbar.jsx

### ISSUE THREAD

**Issue by Harsh-Ojha** [adrianhajdin/project_3D_developer_portfolio#104]
<img width="806" alt="Screenshot 2023-08-31 131500" src="https://github.com/adrianhajdin/project_3D_developer_portfolio/assets/76123482/3df6cd1c-2b5d-4d71-9829-065a568f9993">

The toggle function is not working, and I am unable to close or open the list manually. Please suggest some solution.

**Comment by Tusharknwl** [comment]
@Harsh-Ojha you have to use  ``` ` ``` ( backtick: the key to the left of the 1 in standard keyboards) instead of ``` ' ``` (single quote)

```
             <li
              key={Link.id}
              className={`${
                active === Link.title
                ? "text-white"
                : "text-secondary"
              } hover:text-white text-[18px] font-medium cursor-pointer`}
              onClick={()=> setActive(Link.title)}
              >
              <a href={`#${Link.id}`}>{Link.title}</a>
            </li>
```

**Comment by Harsh-Ojha** [comment]
> @Harsh-Ojha you have to use `` ` `` ( backtick: the key to the left of the 1 in standard keyboards) instead of `'` (single quote)
> 
> ```
>              <li
>               key={Link.id}
>               className={`${
>                 active === Link.title
>                 ? "text-white"
>                 : "text-secondary"
>               } hover:text-white text-[18px] font-medium cursor-pointer`}
>               onClick={()=> setActive(Link.title)}
>               >
>               <a href={`#${Link.id}`}>{Link.title}</a>
>             </li>
> ```

Thanks @Tusharknwl, it worked for me.
