### ISSUE TITLE
THREE.BufferGeometry.computeBoundingSphere(): Computed radius is NaN. The "position" attribute is likely to have NaN values. 

### ISSUE THREAD

**Issue by jaismeenMehra** [adrianhajdin/project_3D_developer_portfolio#118]
I am encountering this issue in stars.jsx compent. Can anyone help me to solve this issue?
![issue](https://github.com/adrianhajdin/project_3D_developer_portfolio/assets/111241686/94bc27b1-2196-4a3d-8390-e97f1ef1788d)

**Comment by Evanrsl** [comment]
check this https://github.com/adrianhajdin/project_3D_developer_portfolio/issues/92#issuecomment-1674549723

**Comment by jaismeenMehra** [comment]
Thank you for your response!!
