### ISSUE TITLE
3D Tech balls do not float

### ISSUE THREAD

**Issue by Noems20** [adrianhajdin/project_3D_developer_portfolio#12]
Unlike the youtube video and the live site the tech 3D balls don't float, when scrolling the balls seems to move a little bit but if I don't scroll or drag they remain static, I am not sure if it's an error on my side but cloning this repo also has that behavior.

Edit: I don't know if it's related but the app crashes in android (Cloning this repo), debugging I found that the 3D balls section causes that error. I don't see the app crashing in the live site https://jsmasterypro.com/ also the balls float as expected but some are not displaying correctly.

Thanks

**Comment by ricardobohadana** [comment]
I can relate to this.
I've been coding together with the youtube video, and after finishing the "Tech" section, the balls do not float.
I also tried to apply any configurations that I might have missed, by looking for differences between my code and this repo, but with no luck.

**Comment by danielmarv** [comment]
Did try to include the right properties to the camera

**Comment by danielmarv** [comment]
Did you also return a primitive to the earth function?

**Comment by Noems20** [comment]
I fixed the floating issue I am not sure if it is the correct approach, in the file Ball.js in the BallCanvas component I removed the attribute frameloop="demand" from the <Canvas>

**Comment by ricardobohadana** [comment]
> I fixed the floating issue I am not sure if it is the correct approach, in the BallCanvas component of the Ball.jsx file I removed the attribute frameloop="demand" from the Canvas

It works!
Removing `frameloop="demand"` from the Canvas inside BallCanvas fixes the issue.

**Comment by kalyansaxena** [comment]
setting frameloop='always' also worked in my case
