### ISSUE TITLE
Error installing Tailwind CSS

### ISSUE THREAD

**Issue by Sagarr124** [adrianhajdin/project_3D_developer_portfolio#125]
I am getting an error after running 'npm install -D tailwindcss' command, can someone help?

![Screenshot 2023-11-26 230303](https://github.com/adrianhajdin/project_3D_developer_portfolio/assets/69119783/dbc3c5bd-1db8-45aa-9270-d2800d91aeba)

![Screenshot 2023-11-26 230339](https://github.com/adrianhajdin/project_3D_developer_portfolio/assets/69119783/42284998-da34-4e0c-b408-90dd1fc086d6)

![Screenshot 2023-11-26 230412](https://github.com/adrianhajdin/project_3D_developer_portfolio/assets/69119783/bfb3258b-5965-417d-923e-d2fbecf2fb13)

**Comment by edmidev** [comment]
Hello @Sagarr124, the first thing that i do is remove the node_modules folder and reinstall with npm i, in the first image i can see that fail remove the folder node_modules\postcss-import.

**Comment by Sagarr124** [comment]
Thank you so much. It worked.
