### ISSUE TITLE
Problem in Computers.jsx component in useGLTF

### ISSUE THREAD

**Issue by jainanurag941** [adrianhajdin/project_3D_developer_portfolio#27]
I am facing problem in this line
`const computer = useGLTF("./desktop_pc/scene.gltf");`
Console gives following error

![error](https://user-images.githubusercontent.com/76944409/225002861-9c779e50-eafd-4d66-a716-b93b40ddaa05.png)
THREE.WebGLRenderer: Context Lost.

Some one please help me with these

**Comment by LinskyUE** [comment]
Make sure the 3d files are on the ./public folder, not on the .src/public

**Comment by jainanurag941** [comment]
Yes the 3d files are on ./public folder only and not on .src/public

**Comment by jainanurag941** [comment]
The problem is there in this line only. If i comment out `const computer = useGLTF("./desktop_pc/scene.gltf");` then everything works fine. The model is not able to load for whatsoever reason.

**Comment by Ajeeth-07** [comment]
> The problem is there in this line only. If i comment out `const computer = useGLTF("./desktop_pc/scene.gltf");` then everything works fine. The model is not able to load for whatsoever reason.
make sure you have imported orbitalControls, preLoad and useGLTF from  react three, it could be the reason that you have not imported libraries

**Comment by Ajeeth-07** [comment]
> > 
> 
> I have included everything `import React, { Suspense, useEffect, useState } from "react"; import { Canvas } from "@react-three/fiber"; import { OrbitControls, Preload, useGLTF } from "@react-three/drei";
> 
> import CanvasLoader from "../Loader";
> 
> const Computers = () => { const computer = useGLTF("./desktop_pc/scene.gltf"); return ( <spotLight position={[-20, 50, 10]} angle={0.12} penumbra={1} intensity={1} castShadow shadow-mapSize={1024} /> <primitive object={computer.scene} scale={0.75} position={[0, -3.25, -1.5]} rotation={[-0.01, -0.2, -0.1]} /> ); };
> 
> const ComputersCanvas = () => { return ( <Canvas frameloop="demand" shadows camera={{ position: [20, 3, 5], fov: 25 }} gl={{ preserveDrawingBuffer: true }} > <Suspense fallback={}> <OrbitControls enableZoom={false} maxPolarAngle={Math.PI / 2} minPolarAngle={Math.PI / 2} />
> 
> ```
>   <Preload all />
> </Canvas>
> ```
> 
> ); };
> 
> export default ComputersCanvas; `

You didn't add a mesh component it is important to render a 3d model. Try adding a mesh component and see if it works
`<mesh>
      <hemisphereLight
        intensity={0.15}
        groundColor="black"
      />
      <pointLight intensity={1}/>`

**Comment by jainanurag941** [comment]
This is the final code still problem not solved
`import React, { Suspense, useEffect, useState } from "react";
import { Canvas } from "@react-three/fiber";
import { OrbitControls, Preload, useGLTF } from "@react-three/drei";

import CanvasLoader from "../Loader";

const Computers = () => {
  const computer = useGLTF("./desktop_pc/scene.gltf");
  return (
    <mesh>
      <hemisphereLight intensity={0.15} groundColor="black" />
      <spotLight
        position={[-20, 50, 10]}
        angle={0.12}
        penumbra={1}
        intensity={1}
        castShadow
        shadow-mapSize={1024}
      />
      <pointLight intensity={1} />
      <primitive
        object={computer.scene}
        scale={0.75}
        position={[0, -3.25, -1.5]}
        rotation={[-0.01, -0.2, -0.1]}
      />
    </mesh>
  );
};

const ComputersCanvas = () => {
  return (
    <Canvas
      frameloop="demand"
      shadows
      camera={{ position: [20, 3, 5], fov: 25 }}
      gl={{ preserveDrawingBuffer: true }}
    >
      <Suspense fallback={<CanvasLoader />}>
        <OrbitControls
          enableZoom={false}
          maxPolarAngle={Math.PI / 2}
          minPolarAngle={Math.PI / 2}
        />
        <Computers />
      </Suspense>

      <Preload all />
    </Canvas>
  );
};

export default ComputersCanvas;
`

**Comment by jainanurag941** [comment]
this is my code
import React, { Suspense, useEffect, useState } from "react";
import { Canvas } from "@react-three/fiber";
import { OrbitControls, Preload, useGLTF } from "@react-three/drei";

import CanvasLoader from "../Loader";

const Computers = () => {
  const computer = useGLTF("./desktop_pc/scene.gltf");
  return (
    <mesh>
      <hemisphereLight intensity={0.15} groundColor="black" />
      <spotLight
        position={[-20, 50, 10]}
        angle={0.12}
        penumbra={1}
        intensity={1}
        castShadow
        shadow-mapSize={1024}
      />
      <pointLight intensity={1} />
      <primitive
        object={computer.scene}
        scale={0.75}
        position={[0, -3.25, -1.5]}
        rotation={[-0.01, -0.2, -0.1]}
      />
    </mesh>
  );
};

const ComputersCanvas = () => {
  return (
    <Canvas
      frameloop="demand"
      shadows
      camera={{ position: [20, 3, 5], fov: 25 }}
      gl={{ preserveDrawingBuffer: true }}
    >
      <Suspense fallback={<CanvasLoader />}>
        <OrbitControls
          enableZoom={false}
          maxPolarAngle={Math.PI / 2}
          minPolarAngle={Math.PI / 2}
        />
        <Computers />
      </Suspense>

      <Preload all />
    </Canvas>
  );
};

export default ComputersCanvas;

**Comment by jainanurag941** [comment]
> > > 
> > 
> > 
> > I have included everything `import React, { Suspense, useEffect, useState } from "react"; import { Canvas } from "@react-three/fiber"; import { OrbitControls, Preload, useGLTF } from "@react-three/drei";
> > import CanvasLoader from "../Loader";
> > const Computers = () => { const computer = useGLTF("./desktop_pc/scene.gltf"); return ( <spotLight position={[-20, 50, 10]} angle={0.12} penumbra={1} intensity={1} castShadow shadow-mapSize={1024} /> <primitive object={computer.scene} scale={0.75} position={[0, -3.25, -1.5]} rotation={[-0.01, -0.2, -0.1]} /> ); };
> > const ComputersCanvas = () => { return ( <Canvas frameloop="demand" shadows camera={{ position: [20, 3, 5], fov: 25 }} gl={{ preserveDrawingBuffer: true }} >  <OrbitControls enableZoom={false} maxPolarAngle={Math.PI / 2} minPolarAngle={Math.PI / 2} />
> > ```
> >   <Preload all />
> > </Canvas>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ); };
> > export default ComputersCanvas; `
> 
> You didn't add a mesh component it is important to render a 3d model. Try adding a mesh component and see if it works `<mesh> <hemisphereLight intensity={0.15} groundColor="black" /> <pointLight intensity={1}/>`

`const Computers = () => {
  const computer = useGLTF("./desktop_pc/scene.gltf");
  return (
    <mesh>
      <hemisphereLight intensity={0.15} groundColor="black" />
      <spotLight
        position={[-20, 50, 10]}
        angle={0.12}
        penumbra={1}
        intensity={1}
        castShadow
        shadow-mapSize={1024}
      />
      <pointLight intensity={1} />
      <primitive
        object={computer.scene}
        scale={0.75}
        position={[0, -3.25, -1.5]}
        rotation={[-0.01, -0.2, -0.1]}
      />
    </mesh>
  );
};`

problem still not solved

**Comment by Ajeeth-07** [comment]
> > 
> 
> I have included everything `import React, { Suspense, useEffect, useState } from "react"; import { Canvas } from "@react-three/fiber"; import { OrbitControls, Preload, useGLTF } from "@react-three/drei";
> 
> import CanvasLoader from "../Loader";
> 
> const Computers = () => { const computer = useGLTF("./desktop_pc/scene.gltf"); return ( <spotLight position={[-20, 50, 10]} angle={0.12} penumbra={1} intensity={1} castShadow shadow-mapSize={1024} /> <primitive object={computer.scene} scale={0.75} position={[0, -3.25, -1.5]} rotation={[-0.01, -0.2, -0.1]} /> ); };
> 
> const ComputersCanvas = () => { return ( <Canvas frameloop="demand" shadows camera={{ position: [20, 3, 5], fov: 25 }} gl={{ preserveDrawingBuffer: true }} > <Suspense fallback={}> <OrbitControls enableZoom={false} maxPolarAngle={Math.PI / 2} minPolarAngle={Math.PI / 2} />
> 
> ```
>   <Preload all />
> </Canvas>
> ```
> 
> ); };
> 
> export default ComputersCanvas; `

`<Suspense fallback={<CanvasLoader/>}`  
try this and see if the code works

**Comment by jainanurag941** [comment]
Yeah that line is added but when i copied and pasted it did not show up here

**Comment by jainanurag941** [comment]
> > > 
> > 
> > 
> > I have included everything `import React, { Suspense, useEffect, useState } from "react"; import { Canvas } from "@react-three/fiber"; import { OrbitControls, Preload, useGLTF } from "@react-three/drei";
> > import CanvasLoader from "../Loader";
> > const Computers = () => { const computer = useGLTF("./desktop_pc/scene.gltf"); return ( <spotLight position={[-20, 50, 10]} angle={0.12} penumbra={1} intensity={1} castShadow shadow-mapSize={1024} /> <primitive object={computer.scene} scale={0.75} position={[0, -3.25, -1.5]} rotation={[-0.01, -0.2, -0.1]} /> ); };
> > const ComputersCanvas = () => { return ( <Canvas frameloop="demand" shadows camera={{ position: [20, 3, 5], fov: 25 }} gl={{ preserveDrawingBuffer: true }} >  <OrbitControls enableZoom={false} maxPolarAngle={Math.PI / 2} minPolarAngle={Math.PI / 2} />
> > ```
> >   <Preload all />
> > </Canvas>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ); };
> > export default ComputersCanvas; `
> 
> `<Suspense fallback={<CanvasLoader/>}` try this and see if the code works

Here is my project repo link
[https://github.com/jainanurag941/portfolio](url)
Can you please check it.
I have watched the video till 1 hour

**Comment by jainanurag941** [comment]
> > > 
> > 
> > 
> > I have included everything `import React, { Suspense, useEffect, useState } from "react"; import { Canvas } from "@react-three/fiber"; import { OrbitControls, Preload, useGLTF } from "@react-three/drei";
> > import CanvasLoader from "../Loader";
> > const Computers = () => { const computer = useGLTF("./desktop_pc/scene.gltf"); return ( <spotLight position={[-20, 50, 10]} angle={0.12} penumbra={1} intensity={1} castShadow shadow-mapSize={1024} /> <primitive object={computer.scene} scale={0.75} position={[0, -3.25, -1.5]} rotation={[-0.01, -0.2, -0.1]} /> ); };
> > const ComputersCanvas = () => { return ( <Canvas frameloop="demand" shadows camera={{ position: [20, 3, 5], fov: 25 }} gl={{ preserveDrawingBuffer: true }} >  <OrbitControls enableZoom={false} maxPolarAngle={Math.PI / 2} minPolarAngle={Math.PI / 2} />
> > ```
> >   <Preload all />
> > </Canvas>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ); };
> > export default ComputersCanvas; `
> 
> `<Suspense fallback={<CanvasLoader/>}` try this and see if the code works

Here is my repo link
https://github.com/jainanurag941/portfolio
can you please check the code
i have watched video till 59:14

**Comment by Ajeeth-07** [comment]
> > > > 
> > > 
> > > 
> > > I have included everything `import React, { Suspense, useEffect, useState } from "react"; import { Canvas } from "@react-three/fiber"; import { OrbitControls, Preload, useGLTF } from "@react-three/drei";
> > > import CanvasLoader from "../Loader";
> > > const Computers = () => { const computer = useGLTF("./desktop_pc/scene.gltf"); return ( <spotLight position={[-20, 50, 10]} angle={0.12} penumbra={1} intensity={1} castShadow shadow-mapSize={1024} /> <primitive object={computer.scene} scale={0.75} position={[0, -3.25, -1.5]} rotation={[-0.01, -0.2, -0.1]} /> ); };
> > > const ComputersCanvas = () => { return ( <Canvas frameloop="demand" shadows camera={{ position: [20, 3, 5], fov: 25 }} gl={{ preserveDrawingBuffer: true }} >  <OrbitControls enableZoom={false} maxPolarAngle={Math.PI / 2} minPolarAngle={Math.PI / 2} />
> > > ```
> > >   <Preload all />
> > > </Canvas>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ); };
> > > export default ComputersCanvas; `
> > 
> > 
> > `<Suspense fallback={<CanvasLoader/>}` try this and see if the code works
> 
> Here is my repo link https://github.com/jainanurag941/portfolio can you please check the code i have watched video till 59:14

check if the gltf file is present in public/desktop folder and if the file is present in the specified folder then close the server and install react three/drei using command `npm install @react-three/drei --legacy-peer-deps`

**Comment by jainanurag941** [comment]
i have installed the package. The loading goes till 96.3% and then screen becomes blank.

**Comment by jainanurag941** [comment]
> > > > > 
> > > > 
> > > > 
> > > > I have included everything `import React, { Suspense, useEffect, useState } from "react"; import { Canvas } from "@react-three/fiber"; import { OrbitControls, Preload, useGLTF } from "@react-three/drei";
> > > > import CanvasLoader from "../Loader";
> > > > const Computers = () => { const computer = useGLTF("./desktop_pc/scene.gltf"); return ( <spotLight position={[-20, 50, 10]} angle={0.12} penumbra={1} intensity={1} castShadow shadow-mapSize={1024} /> <primitive object={computer.scene} scale={0.75} position={[0, -3.25, -1.5]} rotation={[-0.01, -0.2, -0.1]} /> ); };
> > > > const ComputersCanvas = () => { return ( <Canvas frameloop="demand" shadows camera={{ position: [20, 3, 5], fov: 25 }} gl={{ preserveDrawingBuffer: true }} >  <OrbitControls enableZoom={false} maxPolarAngle={Math.PI / 2} minPolarAngle={Math.PI / 2} />
> > > > ```
> > > >   <Preload all />
> > > > </Canvas>
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ); };
> > > > export default ComputersCanvas; `
> > > 
> > > 
> > > `<Suspense fallback={<CanvasLoader/>}` try this and see if the code works
> > 
> > 
> > Here is my repo link https://github.com/jainanurag941/portfolio can you please check the code i have watched video till 59:14
> 
> check if the gltf file is present in public/desktop folder and if the file is present in the specified folder then close the server and install react three/drei using command `npm install @react-three/drei --legacy-peer-deps`

Thank you for your help bro. My problem is now solved. The model is now rendered successfully.
Thanks once again.

**Comment by yashrajp-dot** [comment]
how did you solve the problem?

**Comment by jainanurag941** [comment]
> 

I wrote the exactly same code which the instructor wrote. In my case i had downloaded internet download manager in my laptop and that was causing all the problem. I uninstalled it and everything worked fine after that. IDM was creating problem.

**Comment by Devansh-Mehra** [comment]
> > 
> 
> I wrote the exactly same code which the instructor wrote. In my case i had downloaded internet download manager in my laptop and that was causing all the problem. I uninstalled it and everything worked fine after that. IDM was creating problem.

what was the IDM that u were using?

**Comment by jainanurag941** [comment]
> > > 
> > 
> > 
> > I wrote the exactly same code which the instructor wrote. In my case i had downloaded internet download manager in my laptop and that was causing all the problem. I uninstalled it and everything worked fine after that. IDM was creating problem.
> 
> what was the IDM that u were using?

It was simply "Internet Download Manager". It was not allowing the model to load.

**Comment by Devansh-Mehra** [comment]
> > > > 
> > > 
> > > 
> > > I wrote the exactly same code which the instructor wrote. In my case i had downloaded internet download manager in my laptop and that was causing all the problem. I uninstalled it and everything worked fine after that. IDM was creating problem.
> > 
> > 
> > what was the IDM that u were using?
> 
> It was simply "Internet Download Manager". It was not allowing the model to load.

I don't have IDM but still facing the same issue.

**Comment by jainanurag941** [comment]
> > > > > 
> > > > 
> > > > 
> > > > I wrote the exactly same code which the instructor wrote. In my case i had downloaded internet download manager in my laptop and that was causing all the problem. I uninstalled it and everything worked fine after that. IDM was creating problem.
> > > 
> > > 
> > > what was the IDM that u were using?
> > 
> > 
> > It was simply "Internet Download Manager". It was not allowing the model to load.
> 
> I don't have IDM but still facing the same issue.

In my case IDM was causing the issue.
Otherwise, i followed the code which he wrote. The code is completely fine. There should be some typo or import missing. If the  issue is different, you will have to figure it out.
