### ISSUE TITLE
Balls are static and not floating on the screen

### ISSUE THREAD

**Issue by iamchenyu** [adrianhajdin/project_3D_developer_portfolio#43]
When clicking on the balls, they rotate fine but after loaded to the screen, they just appear static and has no movements. When I scroll up or down, they have a single frame movement but that's it. 

I compared my code inside Ball.jsx file with the tutorial but even if the code are identical, the issue still exists on my side. You can see a live demo [HERE](https://endearing-rugelach-2ca48b.netlify.app/).

Does anyone encounter the same issue and if so, could you please share your solution? Thank you!

**Comment by iamchenyu** [comment]
I figured out that by removing the `frameloop="demand"` attribute on the <Canvas /> element, everything works fine. Hope it helps if someone runs into the same issue.

**Comment by lefty93** [comment]
I also met this issue and add `autoRotate` & `autoRotateSpeed={1.5}` attribute to the <OrbitControls />

**Comment by Vour123** [comment]
@iamchenyu Thank you so much. Was stuck on this for a while.
