### ISSUE TITLE
Deploying to github pages

### ISSUE THREAD

**Issue by lucylanlou** [adrianhajdin/project_3D_developer_portfolio#59]
My site runs perfectly locally on http://localhost:5173/ but when i tried deploying with github pages, I am getting a blank screen with these errors:

![image](https://github.com/adrianhajdin/project_3D_developer_portfolio/assets/34356373/c3dc8933-eca0-42a8-bdaa-0c7084014e06)

Anyone know how to fix these?

**Comment by lucylanlou** [comment]
Resolved, I followed https://vitejs.dev/guide/static-deploy.html#github-pages I got stuck for a bit before I realized the static.yml file the guide uses is different from the default static.yml provided by github. I made sure the matched and it worked!

**Comment by SamyamS** [comment]
@lucylanlou this worked! I had been struggling to deploy it on github pages since yesterday. Thank you :)
