### ISSUE TITLE
[SOLVE] Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/react-tilt.js?v=d6d8354a' does not provide an export named 'default' (at About.jsx:2:8)

### ISSUE THREAD

**Issue by louloudev59** [adrianhajdin/project_3D_developer_portfolio#70]
Hello, when i started the website with npm run dev, everything works but the web page displayed is completely blank and in the browser console, I have this error: `Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/react-tilt.js?v=d6d8354a' does not provide an export named 'default' (at About.jsx:2:8)`

how to fix the bug??

THANKS

**Comment by ExZyO** [comment]
same

**Comment by louloudev59** [comment]
> Same, if you have found the solution please lmk
> 
> UPDATE: i found the solution: https://stackoverflow.com/questions/75989922/i-am-getting-the-error-in-importing-tilt-from-react-while-working-using-vite-an
> 
> Uninstall the package with:
> 
> npm uninstall react-tilt
> 
> Then reinstalled it with:
> 
> npm install react-tilt
> 
> Then change the import in About.jsx and Works.jsx to:
> 
> import { Tilt } from "react-tilt";

thanks a lot

**Comment by developer-sanjay-patidar** [comment]
> Hello, when i started the website with npm run dev, everything works but the web page displayed is completely blank and in the browser console, I have this error: `Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/react-tilt.js?v=d6d8354a' does not provide an export named 'default' (at About.jsx:2:8)`
> 
> how to fix the bug??
> 
> THANKS

issue solved :  try importing tilt as  : import { Tilt } from "react-tilt";

**Comment by Satvik77** [comment]
Just need to replace Tilt to {Tilt} , no extra steps needed
