### ISSUE TITLE
White screen on some models.

### ISSUE THREAD

**Issue by OtaraAlex** [adrianhajdin/project_3D_developer_portfolio#79]
Upon deployment to Vercel, the hero section and some balls load on my pc but turn white on my mobile device. A senior developer has adviced me to try caching and reducing redirects. 
I'd appreciate if someone guides me on how to go about it.

**Comment by zjian107-su** [comment]
@OtaraAlex This error is related to the WebGL contexts, which are used to render 2D and 3D graphics in a web browser.

Each WebGL context consumes memory and GPU resources. There's a limit to how many WebGL contexts you can have at the same time, and when you exceed this limit, the browser starts to drop the oldest ones.

I assume you have the white screen only on the first context such as the "computers" canvas. Try to remove some context items such as your "balls". At least it worked for me. Good luck

**Comment by OtaraAlex** [comment]
Thank you Zijan, it has worked for me too.

**Comment by BitByteSavvy** [comment]
> @OtaraAlex This error is related to the WebGL contexts, which are used to render 2D and 3D graphics in a web browser.
> 
> Each WebGL context consumes memory and GPU resources. There's a limit to how many WebGL contexts you can have at the same time, and when you exceed this limit, the browser starts to drop the oldest ones.
> 
> I assume you have the white screen only on the first context such as the "computers" canvas. Try to remove some context items such as your "balls". At least it worked for me. Good luck


****
This solution worked for me too. If your getting a white screen on the "Computers" section reduce the number of Balls, by going to the constant>>index.js and reduce the number of technologies (name & icon) . try reduce 2 and see if it still renders a white screen. I used 14 Balls and didn't have the issue anymore.
