### ISSUE TITLE
Getting errors while rendering the computers component

### ISSUE THREAD

**Issue by aayushchauhan10** [adrianhajdin/project_3D_developer_portfolio#8]
Hello Adrian, I am getting some errors while rendering the computers component like one of the main error is that Div is not part of the THREE namespace and some other errors too. Can you please help?

**Comment by lukelu520** [comment]
Me too, I got below error when open website by smartphone (while desktop works well though): 

`THREE.BufferGeometry.computeBoundingSphere(): Computed radius is NaN. The "position" attribute is likely to have NaN values. `

**Comment by aayushchauhan10** [comment]
I got these errors but do one thing, close the console, refresh the page and continue over the video. my errors got resolved automatically when I was done with the Loader component. So, yeah, you can also try this.

**Comment by aayushchauhan10** [comment]
Closing this issue because it got resolved after further continue in the video.
