### ISSUE TITLE
CanvasLoader Issue

### ISSUE THREAD

**Issue by pranavv444** [adrianhajdin/project_3D_developer_portfolio#86]
After importing Canvas Loader and using it in Suspense Function my screen is going full white. I don't know what is the probelem in CanvasLoader in Computer.jsx file.Whenever I am commenting the import of canvasloader and the suspense function screen goes normal.Pls help me.

**Comment by TanChunEE** [comment]
Please provide your clear code snippet if the problem persists.

**Comment by zjian107-su** [comment]
#79 
There is a limit of how many canvas you can have on the screen. Hope this one helps!

**Comment by pranavv444** [comment]
the issur is resolved now.
