### ISSUE TITLE
How to fix white screen when importing new assets

### ISSUE THREAD

**Issue by rsbassi9** [adrianhajdin/project_3D_developer_portfolio#93]
My code works, but I want to update the icons for the work experience and tech sections.

I have uploaded the relevant PNG files to the assets folder, but in index.js, whenever I add the files into the "import" section from "../assets", I get a white screen.

I have the relevant files in the same locations as Adrian ( ie, company, tech etc.) but if i add the files into the import statement, I get a white page. 

Anybody know how to fix this?

**Comment by harshit4317** [comment]
You have to change the import and export section of index.js file in the assets folder.

**Comment by arpit-garg-1995** [comment]
There is also an index.js in assets folder, look into that.

**Comment by rsbassi9** [comment]
> There is also an index.js in assets folder, look into that.

Amazing, thanks!  Took me a moment but realized that was the problem
